<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->insert([
            [
                'title' => 'Мясо и колбасы',
                'alias' => 'meat-sausages',
                'img' => 'meat.png',
                'keywords' => 'мясо, колбасы',
                'description' => 'мясо и колбасы',
                'hit' => '1',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Рыба и морепродукты',
                'alias' => 'fish-seafood',
                'img' => 'fish.png',
                'keywords' => 'рыба, морепродукты',
                'description' => 'рыба и морепродукты',
                'hit' => '1',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Овощи и фрукты',
                'alias' => 'vegetables-fruits',
                'img' => 'fruits.png',
                'keywords' => 'овощи, фрукты',
                'description' => 'овощи и фрукты',
                'hit' => '1',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Молоко и молочные продукты',
                'alias' => 'milk-products',
                'img' => 'milk.png',
                'keywords' => 'молоко, молочные продукты',
                'description' => 'молоко и молочные продукты',
                'hit' => '1',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Крупы и каши',
                'alias' => 'cereals-kashas',
                'img' => 'cereals.png',
                'keywords' => 'крупы, каши',
                'description' => 'крупы и каши',
                'hit' => '1',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Чай, кофе и напитки',
                'alias' => 'tea-coffee-drinks',
                'img' => 'tea.png',
                'keywords' => 'чай, кофе, напитки',
                'description' => 'чай, кофе и напитки',
                'hit' => '1',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Сладости',
                'alias' => 'sweets',
                'img' => 'sweets.png',
                'keywords' => 'сладости',
                'description' => 'сладости',
                'hit' => '1',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Свежее мясо',
                'alias' => 'fresh-meat',
                'img' => null,
                'keywords' => 'свежее мясо',
                'description' => 'свежее мясо',
                'hit' => '0',
                'parent_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Вареные колбасы',
                'alias' => 'sausages',
                'img' => null,
                'keywords' => 'вареные колбасы',
                'description' => 'вареные колбасы',
                'hit' => '0',
                'parent_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Копчения',
                'alias' => 'smoked-meats',
                'img' => null,
                'keywords' => 'копчения',
                'description' => 'копчения',
                'hit' => '0',
                'parent_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Рыба',
                'alias' => 'fish',
                'img' => null,
                'keywords' => 'рыба',
                'description' => 'рыба',
                'hit' => '0',
                'parent_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Морепродукты',
                'alias' => 'seafood',
                'img' => null,
                'keywords' => 'морепродукты',
                'description' => 'морепродукты',
                'hit' => '0',
                'parent_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Рыбные полуфабрикаты',
                'alias' => 'fish-products',
                'img' => null,
                'keywords' => 'рыбные полуфабрикаты',
                'description' => 'рыбные полуфабрикаты',
                'hit' => '0',
                'parent_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Овощи',
                'alias' => 'vegetables',
                'img' => null,
                'keywords' => 'овощи',
                'description' => 'овощи',
                'hit' => '0',
                'parent_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Фрукты',
                'alias' => 'fruits',
                'img' => null,
                'keywords' => 'фрукты',
                'description' => 'фрукты',
                'hit' => '0',
                'parent_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Сухофрукты',
                'alias' => 'dried-fruits',
                'img' => null,
                'keywords' => 'сухофрукты',
                'description' => 'сухофрукты',
                'hit' => '0',
                'parent_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Молоко',
                'alias' => 'milk',
                'img' => null,
                'keywords' => 'молоко',
                'description' => 'молоко',
                'hit' => '0',
                'parent_id' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Масло и сыры',
                'alias' => 'butter-cheeses',
                'img' => null,
                'keywords' => 'масло, сыры',
                'description' => 'масло и сыры',
                'hit' => '0',
                'parent_id' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Кефир и йогурты',
                'alias' => 'yoghurts',
                'img' => null,
                'keywords' => 'кефир, йогурт',
                'description' => 'кефир и йогурты',
                'hit' => '0',
                'parent_id' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Крупы',
                'alias' => 'cereals',
                'img' => null,
                'keywords' => 'крупы',
                'description' => 'крупы',
                'hit' => '0',
                'parent_id' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Каши',
                'alias' => 'kashas',
                'img' => null,
                'keywords' => 'каши',
                'description' => 'каши',
                'hit' => '0',
                'parent_id' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],

            [
                'title' => 'Чай',
                'alias' => 'tea',
                'img' => null,
                'keywords' => 'чай',
                'description' => 'чай',
                'hit' => '0',
                'parent_id' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Кофе',
                'alias' => 'coffee',
                'img' => null,
                'keywords' => 'кофе',
                'description' => 'кофе',
                'hit' => '0',
                'parent_id' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Напитки',
                'alias' => 'drinks',
                'img' => null,
                'keywords' => 'напитки',
                'description' => 'напитки',
                'hit' => '0',
                'parent_id' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Торты',
                'alias' => 'cakes',
                'img' => null,
                'keywords' => 'торты',
                'description' => 'торты',
                'hit' => '0',
                'parent_id' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Печенье',
                'alias' => 'biscuits',
                'img' => null,
                'keywords' => 'печенье',
                'description' => 'печенье',
                'hit' => '0',
                'parent_id' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Шоколад',
                'alias' => 'chocolate',
                'img' => null,
                'keywords' => 'шоколад',
                'description' => 'шоколад',
                'hit' => '0',
                'parent_id' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],

        ]);
    }
}
